name: Test Workflow

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
  strategy:
      matrix:
        node-version: [18.x]
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install
        npm install -g ganache-cli

    - name: Start 3 blockchains and run tests
      run: |
        ganache-cli --account="0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef,100000000000000000000000000" -p 8545 > /dev/null 2>&1 &
        PID1=$!
        ganache-cli --account="0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef,100000000000000000000000000" -p 8646 > /dev/null 2>&1 &
        PID2=$!
        ganache-cli --account="0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef,100000000000000000000000000" -p 8747 > /dev/null 2>&1 &
        PID3=$!
        sleep 1
        node bridge.js &
        BRIDGE_PID=$!
        sleep 1
        node test.js
        kill $PID1 $PID2 $PID3 $BRIDGE_PID
